name: Scheduled Web Scraping of Puzzle Title and Leaderboard Data

on:
    schedule:
        - cron: '0 8 1-25 12 *'

jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run script
              run: python puzzle_and_leaderboard_bot.py
