name: Scheduled Web Scraping of Puzzle Title and Leaderboard Data

on:
  schedule:
    - cron: "0 7 1-12 12 *"

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Sync dependencies
        run: uv sync

      - name: Run script
        run: uv run python scrape_title_and_leaderboard.py

      - name: Commit changes to database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add aoc.db
          git commit -m "Add new title & leaderboard to DB" || echo "No changes to commit"
          git pull --rebase
          git push
