name: Scheduled Web Scraping of Completions Stats

on:
  schedule:
    - cron: "0 12 * * *"

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python completion_stats_bot.py

      - name: Commit changes to database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add aoc.db
          git commit -m "Daily database update" || echo "No changes to commit"
          git push
