name: Scheduled Web Scraping of Puzzle Title and Leaderboard Data

on:
  schedule:
    - cron: "0 7 1-25 12 *"

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11 with caching
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scrape_title_and_leaderboard.py

      - name: Commit changes to database
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add aoc.db
          git commit -m "Add new title & leaderboard to DB" || echo "No changes to commit"
          git push
